### ISSUE TITLE
license info request

### ISSUE THREAD

**Issue by leifliddy** [povik/alsa-ucm-conf-asahi#2]
I'd like to create a Fedora package from your project and one of the outstanding issues regards licensing. 
https://bugzilla.redhat.com/show_bug.cgi?id=2143827

Would you be able to add a license to your project?

**Comment by povik** [comment]
Sure, I copied in the LICENSE of upstream alsa-ucm-conf since eventually I expect the contents to be merged into there. Now the project has a BSD-3 license.

**Comment by povik** [comment]
I moved the license file to `LICENSE.asahi` so it doesn't clash with the parent package if people simply copy one tree over the other. I also added a v1 tag for the current tip. Let me know if this is good as it is.

**Comment by leifliddy** [comment]
Perfect, thanks!!

**Comment by leifliddy** [comment]
Arrrggg. The last sticking point is a versioning scheme. 
So the Asahi project referenced the `alsa-ucm-conf-asahi` package as version 0.2 
https://github.com/AsahiLinux/PKGBUILDs/blob/main/alsa-ucm-conf-asahi/PKGBUILD

But I'm not sure where they came up with that. Do you think you could tag a release?
Sorry to be such a pain, but that would help things.
I don't think this package is getting approved otherwise.

The `asahi-scripts` just uses the date as a versioning scheme. 
That's simple enough, where you never really have to think about it.
https://github.com/AsahiLinux/asahi-scripts/tags

BTW, I really appreciate the work you're doing!

**Comment by povik** [comment]
Don't worry, I am happy to sort this out. I did the v1 tag, but forgot to push it until now. Is that good enough?

**Comment by leifliddy** [comment]
Yup, that works. Thanks again!

**Comment by povik** [comment]
@leifliddy FYI we moved the repo under the AsahiLinux organisation. The old download links like

https://github.com/povik/alsa-ucm-conf-asahi/archive/refs/tags/v1.tar.gz

still work, I checked, but this will be the canonical home going forward.
